### ISSUE TITLE
Remove smells in View package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#105]
- src/logic/view/Client.java
  - Make the enclosing method "static" or remove this set. 21
- src/logic/view/Context.java
  - Immediately return this expression instead of assigning it to the temporary variable "root" 41
  - Complete the task associated to this TODO comment. 55
- src/logic/view/ViewLogin.java
  - This block of commented-out lines of code should be removed. 27
  - Remove these unused method parameters. 39
  - This block of commented-out lines of code should be removed. 44
  - This block of commented-out lines of code should be removed. 51
  - Remove this redundant jump. 75
- src/logic/view/ViewSignUp.java
  - Define a constant instead of duplicating this literal "Form Error!" 10 times 113
  - Remove this redundant jump. 169
  - Complete the task associated to this TODO comment 224

**Comment by mihaiJianu** [comment]
Committed on revision 135.
