### ISSUE TITLE
Rename all packages with lowercase chars

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#11]
Example: logic.compliant.name

**REMEMBER:** Assert that directories are renamed too, according to packages' new names

**Comment by mihaiJianu** [comment]
Commited on revision 28.

**Comment by Torkin1** [comment]
There are some packages with non compliant names yet

**Comment by mihaiJianu** [comment]
still missing some

**Comment by mihaiJianu** [comment]
Committed on revision 30.

**Comment by Torkin1** [comment]
There are some packages with non compliant names yet (again)

**Comment by Torkin1** [comment]
fixed in revision 33 (finally)
