### ISSUE TITLE
remove smells in view package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#118]
- src/logic/view/ViewFlow.java
  - Remove these unused method parameters: location, resources. 34
  - Remove this unused private "showAlert" method. 56
- src/logic/view/ViewLogin.java
  - Remove these unused method parameters: location, resources 58
- src/logic/view/ViewSignUp.java
  - Use the built-in formatting to construct this argument. 151
  - Use the built-in formatting to construct this argument. 158
  - Remove this useless assignment to local variable "todayDay". 164
  - Remove this unused "todayDay" local variable 164
  - Remove this useless assignment to local variable "todayMonth" 165
  - Remove this unused "todayMonth" local variable. 165
  - Either remove or fill this block of code. 189
  -

**Comment by mihaiJianu** [comment]
Committed on revision 152.
