### ISSUE TITLE
Remove smells in view package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#151]
- src/logic/view/ViewFlow.java
  - This block of commented-out lines of code should be removed. 37
- src/logic/view/ViewLogin.java
  - Define a constant instead of duplicating this literal "In the login username is: " 3 times. 127
- src/logic/view/ViewSignUp.java
  -  Replace this use of System.out or System.err by a logger. 142

**Comment by mihaiJianu** [comment]
Committed on revision 176.
