### ISSUE TITLE
smells in misc package 

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#172]
- src/logic/misc/ReflectionMiscellaneous.java
  - Use the built-in formatting to construct this argument. 38
- src/logic/misc/Type.java
  - Rename this constant name to match the regular expression '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$ 4 (Type, Offer --> TYPE, OFFER)

**Comment by mihaiJianu** [comment]
Committed revision 202.
