### ISSUE TITLE
smells in view package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#173]
- src/logic/view/ViewMakeAnAd.java
  - Make the enclosing method "static" or remove this set. 60 
  - Make the enclosing method "static" or remove this set. 65
- src/logic/view/ViewRegulations.java
  - This block of commented-out lines of code should be removed 34
- src/logic/view/ViewUser.java
  - Remove these unused method parameters. 41 (locationUser, resourcesUser )

**Comment by mihaiJianu** [comment]
Committed revision 201.
