### ISSUE TITLE
duplicated lines of code

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#174]
ViewRegulations 35-49 <=> ViewCurriculMainPage 39-53
ViewRegulations 50-66 <=> ViewCurriculumMainPage 84-100
ViewRegulation 67-85 <=> ViewCurriculumMainPage 104-122 <=> ViewMap 73-90
ViewCurriculMainPage 91-122 <=>  ViewMap 59-90

**Comment by mihaiJianu** [comment]
Committed revision 200.
