### ISSUE TITLE
Smells in View package (part 1)

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#191]
- src/logic/view/CheckEmptyField.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 38
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 48
- src/logic/view/Context.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 35
- src/logic/view/InitialState.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 22 - 34
- src/logic/view/View.java
  - Use the built-in formatting to construct this argument.Why is this an issue? 23
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 23
  - Make the enclosing method "static" or remove this set.Why is this an issue? 28
  - This block of commented-out lines of code should be removed.Why is this an issue? 71 - 81
- src/logic/view/ViewComponent.java
  - Convert the abstract class "ViewComponent" into an interface.Why is this an issue? 5
- src/logic/view/ViewCurriculumMainPageController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 29 - 31
  - This block of commented-out lines of code should be removed.Why is this an issue? 37

**Comment by mihaiJianu** [comment]
256.
