### ISSUE TITLE
Smells in View package (part 2)

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#192]
- src/logic/view/ViewFlowController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 22-23
  - This block of commented-out lines of code should be removed.Why is this an issue? 32-35
  - This block of commented-out lines of code should be removed.Why is this an issue? 46
  - This block of commented-out lines of code should be removed.Why is this an issue? 77
- src/logic/view/ViewMakeAnAdController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 52
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 136
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 159
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 171
- src/logic/view/ViewMapController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 32
- src/logic/view/ViewRegulationsController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 29
- src/logic/view/ViewSignUp.java
  - Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. 17
- src/logic/view/ViewSignupController.java
  - Rename this method name to match the regular expression '^[a-z][a-zA-Z0-9]*$'.Why is this an issue?
- src/logic/view/ViewUserController.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 44
-

**Comment by mihaiJianu** [comment]
Committed revision 260.
