### ISSUE TITLE
smells in viewcomponent package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#193]
- src/logic/viewcomponents/CurriculumMainPageCompononent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 27
- src/logic/viewcomponents/FrameComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 24
- src/logic/viewcomponents/LoginComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 28
- src/logic/viewcomponents/MakeAnAdComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 28
- src/logic/viewcomponents/RegulationsComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 27
- src/logic/viewcomponents/SignUpComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 27
- src/logic/viewcomponents/ToolBarComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 24
- src/logic/viewcomponents/ToolBarController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 36 - 40
  - Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.Why is this an issue? 98
- src/logic/viewcomponents/UserComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 27
- src/logic/viewcomponents/ViewComponent.java
  - Convert the abstract class "ViewComponent" into an interface.Why is this an issue? 5
- src/logic/viewcomponents/ViewFlowComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 29
- src/logic/viewcomponents/ViewMapComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 28
- src/logic/viewcomponents/ViewValidateAFavorComponent.java
  - Format specifiers or lambda should be used instead of string concatenation.Why is this an issue? 27

**Comment by mihaiJianu** [comment]
Committed revision 251.
