### ISSUE TITLE
Remove Smells in DAO package

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#239]
- [x]  src/logic/dao/DAOAnswer.java

  - Rename this local variable to match the regular expression '^[a-z][a-zA-Z0-9]*$'.Why is this an issue? 10

- [x]  src/logic/dao/DAOAnswerSerialize.java

  - Remove this unused import 'logic.entity.Favor'.Why is this an issue? 12

- [x]  src/logic/dao/DAOFactory.java

  - Complete the task associated to this TODO comment.Why is this an issue? 27
  - Remove this method and declare a constant for this value.Why is this an issue? 29

- [x]  src/logic/dao/DAOSerialize.java

  - Complete the task associated to this TODO comment.Why is this an issue? 33
  - Invoke method(s) only conditionally.Why is this an issue? 49
  - Use "java.nio.file.Files#delete" here for better messages on error conditions.Why is this an issue? 78

**PLEASE NOTE:** Remove *all* the smells, even the TODO ones.

**Comment by mihaiJianu** [comment]
done in revision 353, 354 and 355 are just to remove a log tha i couldn't resolve Invoke method(s) only conditionally.Why is this an issue? 49 printend the above thing, just info logger! nothing more!
