### ISSUE TITLE
Remove smells in View package (part 1)

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#240]
- [x] src/.../view/components/FavorDetailsBean.java
    - Remove this empty statement.Why is this an issue? 26

- [x]  src/.../view/components/ViewAdController.java
  - String contains no format specifiers.Why is this an issue? 91
  - %n should be used in place of \n to produce the platform-specific line separator.Why is this an issue? 91

- [x]  src/.../view/components/ViewCheckAnswersController.java
  - Remove this unused method parameter "event".Why is this an issue? 97
  - Remove this unused method parameter "event".Why is this an issue? 124
  - Remove this redundant jump.Why is this an issue? 170
  - Remove this unused method parameter "event".Why is this an issue? 186
  - Remove this redundant jump.Why is this an issue? 219

- [x]  src/.../view/components/ViewFlowController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 74
  - Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.Why is this an issue? 126
  - Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.Why is this an issue? 133
  - Refactor the code in order to not assign to this loop counter from within the loop body.Why is this an issue? 240

- [x] src/.../view/components/ViewMakeAnAdController.java
  - Remove the "nextViewM" field and declare it as a local variable in the relevant methods.Why is this an issue? 67
  - This block of commented-out lines of code should be removed.Why is this an issue? 211

**Comment by mihaiJianu** [comment]
Remove this redundant jump.Why is this an issue? 170 (deleted else return;)

Refactor the code in order to not assign to this loop counter from within the loop body.Why is this an issue? 240 (deleted i--; in the if statement)

They suggest to delete this methods, not sure if it change the procedure! check in case!

**Comment by mihaiJianu** [comment]
Committed revision 349 and one in 350.
