### ISSUE TITLE
Remove smells in View package (part 2)

### ISSUE THREAD

**Issue by Torkin1** [LorenzoMei/iNeed#242]
- [x]  src/.../view/components/ViewMapController.java

  - Complete the task associated to this TODO comment.Why is this an issue? 26
  - This block of commented-out lines of code should be removed.Why is this an issue? 28
- [x] src/.../view/components/ViewUserController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 37
  - This block of commented-out lines of code should be removed.Why is this an issue? 45
- [x] src/.../view/components/ViewValidateAFavorController.java
  - Remove this unused import 'logic.checkanswersofanad.AnswerAlreadyAcceptedException'.Why is this an issue? 36
  - Remove this unused import 'logic.checkanswersofanad.CheckAnswersController'.Why is this an issue? 37
  - Remove this unused import 'logic.checkanswersofanad.RequestAdHasAlreadyAnAnswerAcceptedException'.Why is this an issue? 38
  - Complete the task associated to this TODO comment.Why is this an issue? 55
  - Either remove or fill this block of code.Why is this an issue? 76
  - Complete the task associated to this TODO comment.Why is this an issue? 101
  - Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.Why is this an issue? 130
  - Rename this class name to match the regular expression '^[A-Z][a-zA-Z0-9]*$'.Why is this an issue? 137
- [x] src/.../view/components/ViewWalletController.java
  - This block of commented-out lines of code should be removed.Why is this an issue? 36

**Comment by mihaiJianu** [comment]
Deleted the todo part, but still not implemented by choice.

**Comment by mihaiJianu** [comment]
Committed revision 3
